# ===================================================================
# Spring Boot configuration.
#
# Overriding logic applicable here,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Reference for command spring boot properties can be found at
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

#Default port is 8761
server:
  port: ${vcap.application.port:8761}

spring:
  application:
    name: commute-service-discovery

management:
  context-path: /management


eureka:
  instance:
    hostname: localhost
  client: # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${vcap.services.commute-service-discovery.credentials.uri:http://localhost:8761}/eureka/

#security:
#  user:
#    name: commute-dev
#    password: chengeit
